### PR TITLE
Add the meta to events.json

### PR DESCRIPTION
**Pull request by sodre**
See https://developer.github.com/v3/activity/events/types/#metaevent for more details.

### CODE REVIEW

**Comment by khornberg** [comment]
Thanks for the addition. I need to fix the build it seems

**Comment by sodre** [comment]
I know you’re planning to auto generate the web hooks. Is the plan to include them in octokit-routes, or in a new repo?

**Comment by khornberg** [comment]
I like the simplicity of adding them to `octokit-routes`

**Comment by sodre** [comment]
I'm closing this PR since we updated octokitpy-routes to events.json.

**Pull request closed without merging**
